### ISSUE TITLE
Animation handler, animate game entities on backdrop.

### ISSUE THREAD

**Issue by RyanCHaynes** [CS3398-Cerulean-HelloWorld/CS3398-Cerulean-S2016#36]
Create an animation handler that will animate sprite sheets making the game more aesthetically pleasing. These animations consist of graphical assets that are incremented pixally on a map (AKA a sprite sheet).

**Comment by ZWesterman** [comment]
nobody is assigned to this issue. Were you going to add this feature yourself, or is it just an feature planned for a later sprint?

EDIT: 
I also noticed this is not assigned to the "Sprint 1" milestone. I'm going to assume it is planned for a later sprint, and move it to the backlog.

**Comment by RyanCHaynes** [comment]
No me, Kyle and Donovan are going to do all these on Tuesday to round out our graphical API. By the end  (graphically) we will have a background and two animated sprites placed on the background facing one another. (We implemented much more in code but this is what we will able to demo in class)

**Comment by sm422** [comment]
I'm a bit confused.  It looks like this was meant to be done in Sprint 1, but you pulled it out and put it into Sprint 2.   It is now marked done.  Is it?
